import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const forecasts = sqliteTable("forecasts", {
  id: text("id").primaryKey(),
  repository: text("repository").notNull(),
  repoFullName: text("repo_full_name").notNull(),
  createdAt: integer("created_at").notNull(),
  dueAt: integer("due_at").notNull(),
  baselineStars: integer("baseline_stars").notNull(),
  baselinePushedAt: text("baseline_pushed_at"),
  starThreshold: integer("star_threshold").notNull(),
  trendProbability: integer("trend_probability").notNull(),
  opportunityScore: integer("opportunity_score"),
  evidenceQuality: text("evidence_quality").notNull(),
  status: text("status").notNull().default("pending"),
  outcome: integer("outcome"),
  resolvedAt: integer("resolved_at"),
  observedStars: integer("observed_stars"),
  observedPushedAt: text("observed_pushed_at"),
  brier: real("brier"),
  assessmentJson: text("assessment_json").notNull(),
}, (table) => [index("forecasts_status_due_idx").on(table.status, table.dueAt)]);

export const agentRuns = sqliteTable("agent_runs", {
  id: text("id").primaryKey(),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
  status: text("status").notNull().default("predicted"),
  mode: text("mode").notNull(),
  task: text("task").notNull(),
  repository: text("repository").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  runnerName: text("runner_name"),
  profileId: text("profile_id"),
  profileVersion: text("profile_version"),
  definitionHash: text("definition_hash"),
  taskClass: text("task_class"),
  selectionStrategy: text("selection_strategy"),
  successProbability: integer("success_probability").notNull(),
  rawProbability: integer("raw_probability"),
  calibratedProbability: integer("calibrated_probability"),
  calibrationMethod: text("calibration_method"),
  calibrationSampleSize: integer("calibration_sample_size"),
  calibrationMetadataJson: text("calibration_metadata_json"),
  route: text("route").notNull(),
  risk: text("risk").notNull(),
  startedAt: integer("started_at"),
  resolvedAt: integer("resolved_at"),
  testCommand: text("test_command"),
  buildCommand: text("build_command"),
  testPassed: integer("test_passed"),
  buildPassed: integer("build_passed"),
  diffWithinScope: integer("diff_within_scope"),
  diffFiles: integer("diff_files"),
  diffAdditions: integer("diff_additions"),
  diffDeletions: integer("diff_deletions"),
  baselineCommit: text("baseline_commit"),
  finalCommit: text("final_commit"),
  outcome: integer("outcome"),
  brier: real("brier"),
  rawBrier: real("raw_brier"),
  calibratedBrier: real("calibrated_brier"),
  failureCode: text("failure_code"),
  failureSummary: text("failure_summary"),
  assessmentJson: text("assessment_json").notNull(),
  verificationJson: text("verification_json"),
}, (table) => [
  index("agent_runs_status_created_idx").on(table.status, table.createdAt),
  index("agent_runs_model_resolved_idx").on(table.model, table.resolvedAt),
  index("agent_runs_runner_resolved_idx").on(table.runnerName, table.resolvedAt),
  index("agent_runs_profile_resolved_idx").on(table.profileId, table.resolvedAt),
  index("agent_runs_task_class_resolved_idx").on(table.taskClass, table.resolvedAt),
]);

export const agencyVotes = sqliteTable("agency_votes", {
  id: text("id").primaryKey(),
  runId: text("run_id").notNull().references(() => agentRuns.id),
  createdAt: integer("created_at").notNull(),
  resolvedAt: integer("resolved_at"),
  profileId: text("profile_id").notNull(),
  profileName: text("profile_name").notNull(),
  profileVersion: text("profile_version"),
  definitionHash: text("definition_hash"),
  probability: integer("probability").notNull(),
  rawProbability: integer("raw_probability"),
  calibratedProbability: integer("calibrated_probability"),
  confidence: text("confidence"),
  risk: text("risk"),
  route: text("route"),
  verdict: text("verdict"),
  findingsJson: text("findings_json"),
  vetoReason: text("veto_reason"),
  calibrationMetadataJson: text("calibration_metadata_json"),
  metadataJson: text("metadata_json"),
  outcome: integer("outcome"),
  brier: real("brier"),
  rawBrier: real("raw_brier"),
  calibratedBrier: real("calibrated_brier"),
}, (table) => [
  index("agency_votes_run_idx").on(table.runId),
  index("agency_votes_profile_resolved_idx").on(table.profileId, table.resolvedAt),
]);
