import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const forecasts = sqliteTable("forecasts", {
  id: text("id").primaryKey(),
  repository: text("repository").notNull(),
  repoFullName: text("repo_full_name").notNull(),
  createdAt: integer("created_at").notNull(),
  dueAt: integer("due_at").notNull(),
  baselineStars: integer("baseline_stars").notNull(),
  baselinePushedAt: text("baseline_pushed_at"),
  starThreshold: integer("star_threshold").notNull(),
  trendProbability: integer("trend_probability").notNull(),
  opportunityScore: integer("opportunity_score"),
  evidenceQuality: text("evidence_quality").notNull(),
  status: text("status").notNull().default("pending"),
  outcome: integer("outcome"),
  resolvedAt: integer("resolved_at"),
  observedStars: integer("observed_stars"),
  observedPushedAt: text("observed_pushed_at"),
  brier: real("brier"),
  assessmentJson: text("assessment_json").notNull(),
}, (table) => [index("forecasts_status_due_idx").on(table.status, table.dueAt)]);

export const agentRuns = sqliteTable("agent_runs", {
  id: text("id").primaryKey(),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
  status: text("status").notNull().default("predicted"),
  mode: text("mode").notNull(),
  task: text("task").notNull(),
  repository: text("repository").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  runnerName: text("runner_name"),
  successProbability: integer("success_probability").notNull(),
  route: text("route").notNull(),
  risk: text("risk").notNull(),
  startedAt: integer("started_at"),
  resolvedAt: integer("resolved_at"),
  testCommand: text("test_command"),
  buildCommand: text("build_command"),
  testPassed: integer("test_passed"),
  buildPassed: integer("build_passed"),
  diffWithinScope: integer("diff_within_scope"),
  diffFiles: integer("diff_files"),
  diffAdditions: integer("diff_additions"),
  diffDeletions: integer("diff_deletions"),
  baselineCommit: text("baseline_commit"),
  finalCommit: text("final_commit"),
  outcome: integer("outcome"),
  brier: real("brier"),
  failureCode: text("failure_code"),
  failureSummary: text("failure_summary"),
  assessmentJson: text("assessment_json").notNull(),
  verificationJson: text("verification_json"),
}, (table) => [
  index("agent_runs_status_created_idx").on(table.status, table.createdAt),
  index("agent_runs_model_resolved_idx").on(table.model, table.resolvedAt),
  index("agent_runs_runner_resolved_idx").on(table.runnerName, table.resolvedAt),
]);
